# Generated by Django 5.0.6 on 2025-07-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_task_workentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
