# Generated by Django 5.0.6 on 2025-07-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_workentry_unique_together_project_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='employee_id'),
        ),
    ]
