# Generated by Django 5.0.6 on 2025-10-03 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('kochi', 'Kochi'), ('dubai', 'Dubai')], max_length=20)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('semi-admin', 'semi-admin'), ('user', 'user')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.worklocation'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.worklocation'),
        ),
    ]
