# Generated by Django 5.0.6 on 2025-10-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='work_location',
            field=models.CharField(choices=[('kochi', 'Kochi'), ('dubai', 'Dubai')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('semi-admin', 'semi-admin'), ('user', 'user')], default='user', max_length=20),
        ),
    ]
