# Generated by Django 5.0.6 on 2025-10-03 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_worklocation_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='work_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.worklocation'),
            preserve_default=False,
        ),
    ]
