# Generated by Django 5.0.6 on 2025-10-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_customuser_work_location'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workentry',
            constraint=models.CheckConstraint(check=models.Q(('working_hours__gte', 0.1), ('working_hours__lte', 24)), name='valid_working_hours_range'),
        ),
    ]
