# Generated by Django 5.0.6 on 2025-10-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_worklocation_alter_customuser_work_location'),
        ('home', '0007_workentry_valid_working_hours_range'),
    ]

    operations = [
    ]
