# Generated by Django 5.2.4 on 2025-12-05 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20251008_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_lead_engineer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='allocated_draftsman_manhours',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='allocated_engineer_manhours',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='work_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.worklocation'),
            preserve_default=False,
        ),
    ]
