# Generated by Django 5.2.4 on 2025-12-05 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_customuser_is_lead_engineer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lead_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_engineer', to=settings.AUTH_USER_MODEL),
        ),
    ]
