# Generated by Django 5.2.4 on 2025-12-05 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_project_lead_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workentry',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_entry_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workentry',
            name='is_edited_by_lead_engineer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='allocated_draftsman_manhours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='allocated_engineer_manhours',
            field=models.FloatField(default=0),
        ),
    ]
