# Generated by Django 5.2.7 on 2026-02-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_workentry_approval_date_workentry_approval_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="work_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.worklocation",
            ),
        ),
    ]
